# Generated by Django 5.1.2 on 2024-10-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_mychatmodel_delete_mychats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyChatModel',
        ),
    ]
