# Generated by Django 5.1.2 on 2024-10-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0006_delete_mychatmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField()),
                ('me', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
                ('myfriend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myfriend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
