# Generated by Django 5.1.2 on 2024-10-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chatmessage_sender_mychatmodel_delete_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychatmodel',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='chats',
            field=models.JSONField(default=dict),
        ),
    ]
