# Generated by Django 5.1.2 on 2024-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_mychatmodel_message_alter_mychatmodel_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mychatmodel',
            name='message',
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='chats',
            field=models.JSONField(),
        ),
    ]
