# Generated by Django 5.1.2 on 2024-10-29 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_mychatmodel_message_alter_mychatmodel_chats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychatmodel',
            name='chats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='frnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
