# Generated by Django 5.1.2 on 2024-10-31 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_mychatmodel_chats_alter_mychatmodel_frnd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychatmodel',
            name='chats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='frnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_frnd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mychatmodel',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
