# Generated by Django 5.1.2 on 2024-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_remove_mychatmodel_chats_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychatmodel',
            name='chats',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
