# Generated by Django 5.1.2 on 2024-10-31 22:23
from django.db import migrations
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    MychatModel = apps.get_model('chat', 'MychatModel')
    duplicates = MychatModel.objects.values('me_id', 'frnd_id').annotate(count=Count('id')).filter(count__gt=1)
    for duplicate in duplicates:
        MychatModel.objects.filter(me_id=duplicate['me_id'], frnd_id=duplicate['frnd_id']).exclude(
            pk=MychatModel.objects.filter(me_id=duplicate['me_id'], frnd_id=duplicate['frnd_id']).first().pk
        ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0017_mychatmodel_chats_delete_message'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='mychatmodel',
            unique_together={('me_id', 'frnd_id')},
        ),
    ]

