# Generated by Django 5.1.2 on 2024-11-20 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_mychatmodel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mychatmodel',
            unique_together={('me', 'frnd')},
        ),
    ]
