# Generated by Django 5.1.2 on 2024-12-08 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_friend',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_requested',
        ),
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='account_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
