# Generated by Django 5.1.2 on 2024-12-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_is_friend_remove_account_is_requested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='avatar',
            new_name='image',
        ),
    ]
