# Generated by Django 5.1.2 on 2024-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_avatar_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
