# Generated by Django 5.1.2 on 2024-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isIntraUser',
            field=models.BooleanField(default=True),
        ),
    ]
