# Generated by Django 5.1.2 on 2024-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alwaysDisable2fa',
            field=models.BooleanField(default=False),
        ),
    ]
