# Generated by Django 5.1.2 on 2024-11-22 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpaddle',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='playerpaddle',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player_2',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='PlayerPaddle',
        ),
    ]
