# Generated by Django 5.1.2 on 2024-11-22 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamesession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='player_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
