# Generated by Django 5.1.2 on 2024-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamesession_player_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ball_position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ball_position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_one_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_two_position',
            field=models.FloatField(default=0.0),
        ),
    ]
