# Generated by Django 5.1.2 on 2024-11-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_ball_position_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='ball_position_x',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='ball_position_y',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player_one_position',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player_two_position',
        ),
    ]
