# Generated by Django 5.1.2 on 2024-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_gamesession_ball_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ball_velocity_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ball_velocity_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ball_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ball_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paddle_one_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paddle_two_y',
            field=models.FloatField(default=0),
        ),
    ]
